apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: getting-started-servicemonitor
  namespace: des
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: getting-started
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
